In [1]:
import tensorflow as tf

In [2]:
tf

<module 'tensorflow' from 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\__init__.py'>

In [3]:
import numpy as np

In [5]:
# Create Tensors
a=tf.constant([1,2,3]) #Vector tensor
b=tf.constant([4,5,6])

print("Tensor a: ",a)
print("Tensor b: ",b)

Tensor a:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor b:  tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [6]:
a[1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [10]:
# Create Tensors
x=tf.constant([[1,2,3],[7,8,9]]) #Matrix tensor
y=tf.constant([[4,5],[6,2]])

print("Tensor x: ",x)
print("Tensor y: ",y)

Tensor x:  tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int32)
Tensor y:  tf.Tensor(
[[4 5]
 [6 2]], shape=(2, 2), dtype=int32)


In [11]:
# Create Tensors
z=tf.constant([[[1,2,3],[7,8,9]],[[0,2,5],[7,6,8]]]) #3 dimensional Tensor containing two 2x3 matrices

print("Tensor z: ",z)

Tensor z:  tf.Tensor(
[[[1 2 3]
  [7 8 9]]

 [[0 2 5]
  [7 6 8]]], shape=(2, 2, 3), dtype=int32)


In [12]:
a+b #adding two tensors same as tf.add()

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [13]:
c=tf.add(a,b)
print("Addition of two vector tensors is : ",c)

Addition of two vector tensors is :  tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [14]:
s=tf.subtract(a,b)
s

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

In [15]:
a-b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

In [16]:
type(s)

tensorflow.python.framework.ops.EagerTensor

In [19]:
s.numpy() #represent Tensor as array

array([-3, -3, -3])

In [18]:
type(s)

tensorflow.python.framework.ops.EagerTensor

In [20]:
m=tf.multiply(a,b)

In [21]:
m

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

In [22]:
a/b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [23]:
tf.divide(a,b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [25]:
a//b #division result in integer form

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [26]:
b//a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 2])>

In [27]:
# Matrix Multiplication
a_matrix=tf.constant([[1,2],[3,4]])
b_matrix=tf.constant([[5,6],[7,8]])
g=tf.matmul(a_matrix,b_matrix)
print("Matrix multiplication is ",g)

Matrix multiplication is  tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [28]:
g.numpy()

array([[19, 22],
       [43, 50]])